export {default as SearchIco } from './SearchIco';
export {default as PinIco } from './PinIco';
export {default as BasketIco } from './BasketIco';
export {default as CartIco } from './CartIco';
export {default as SidebarBanner } from './SidebarBanner';
export {default as DiscountIco } from './DiscountIco';
export {default as DeleteIco } from './DeleteIco';
export {default as LocationIco } from './LocationIco';
export {default as OpenIco } from './OpenIco';
export {default as CopyIco } from './CopyIco';
export {default as HomeIco} from './HomeIco';
export { default as AvatarIco } from './AvatarIco';
export { default as FbIco } from './FbIco';
export { default as InstaIco } from './InstaIco';
export { default as VkIco } from './VkIco';
export { default as ArrowRight } from './ArrowRight';
export { default as ArrowLeft } from './ArrowLeft';
export { default as ArrowDown } from './ArrowDown';
export { default as BellIco } from './BellIco';
export { default as InfoIco } from './InfoIco';
export { default as CheckIco } from './CheckIco';
export { default as StarIco } from './StarIco';
export { default as ThumbIco } from './ThumbIco';
export { default as CancelIco } from './CancelIco';
export { default as ToggleIco } from './ToggleIco';
